vscode:
  extensions:
    - Shan.code-settings-sync@3.4.3:lADxYq3EKc+4gqNNppMuiQ==
    - dbaeumer.vscode-eslint@1.9.1:YVcwmzKVVl+zZ+wMB02GjQ==
    - esbenp.prettier-vscode@2.3.0:1F0Pvb/ORZ/T+b60LIMs8w==